import { createFileRoute } from "@tanstack/react-router"
import { Markdown } from "../components/Markdown.js"
import { docsContent } from "../docs/content.js"

export const Route = createFileRoute("/docs/cli")({
  head: () => ({ meta: [{ title: "CLI · Grayhaven Nerve" }] }),
  component: Page
})

// Single source: this markdown also ships as /docs/cli.md for agents
// (and inside llms-full.txt), generated by scripts/gen-llms.ts.
function Page() {
  return (
    <>
      <span className="spec-tag">CLI</span>
      <Markdown src={docsContent("cli")} />
    </>
  )
}
