import { createFileRoute } from "@tanstack/react-router"
import { Markdown } from "../components/Markdown.js"
import src from "../../docs-content/quickstart.md?raw"

export const Route = createFileRoute("/docs/")({
  component: Page
})

// Single source: this markdown also ships as /docs/quickstart.md for agents
// (and inside llms-full.txt), generated by scripts/gen-llms.ts.
function Page() {
  return (
    <>
      <span className="spec-tag">Quickstart</span>
      <Markdown src={src} />
    </>
  )
}
