import { createFileRoute } from "@tanstack/react-router"
import { Markdown } from "../components/Markdown.js"
import { docsContent } from "../docs/content.js"

export const Route = createFileRoute("/docs/ai")({
  component: Page
})

// Single source: this markdown also ships as /docs/ai.md for agents
// (and inside llms-full.txt), generated by scripts/gen-llms.ts.
function Page() {
  return (
    <>
      <span className="spec-tag">autonerve</span>
      <Markdown src={docsContent("ai")} />
    </>
  )
}
