import { createFileRoute } from "@tanstack/react-router"
import { useSuspenseQuery } from "@tanstack/react-query"
import { compileQueryOptions } from "../lib/compile-client.js"

export const Route = createFileRoute("/projects/$projectId/board")({
  component: BoardView
})

function BoardView() {
  const { projectId } = Route.useParams()
  const { data } = useSuspenseQuery(compileQueryOptions(projectId))
  return (
    <div
      className="diagram-pane"
      // Generated by our own deterministic board renderer from HIR.
      dangerouslySetInnerHTML={{ __html: data.boardSvg }}
    />
  )
}
