import { createFileRoute } from "@tanstack/react-router"
import { useCompile } from "../lib/compile-client.js"

export const Route = createFileRoute("/projects/$projectId/board")({
  component: BoardView
})

function BoardView() {
  const { projectId } = Route.useParams()
  const { data } = useCompile(projectId)
  if (data === undefined) return null
  return (
    <div
      className="diagram-pane"
      // Generated by our own deterministic board renderer from HIR.
      dangerouslySetInnerHTML={{ __html: data.boardSvg }}
    />
  )
}
