import { createFileRoute } from "@tanstack/react-router"
import { useCompile } from "../lib/compile-client.js"

export const Route = createFileRoute("/projects/$projectId/diagram")({
  component: DiagramView
})

function DiagramView() {
  const { projectId } = Route.useParams()
  const { data } = useCompile(projectId)
  if (data === undefined) return null
  return (
    <div
      className="diagram-pane"
      // The SVG is generated by our own deterministic renderer from HIR.
      dangerouslySetInnerHTML={{ __html: data.svg }}
    />
  )
}
