/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as DocsSdkRouteImport } from './routes/docs.sdk'
import { Route as DocsRulesRouteImport } from './routes/docs.rules'
import { Route as DocsDslRouteImport } from './routes/docs.dsl'
import { Route as DocsCliRouteImport } from './routes/docs.cli'
import { Route as DocsArtifactsRouteImport } from './routes/docs.artifacts'
import { Route as DocsAiRouteImport } from './routes/docs.ai'
import { Route as ProjectsProjectIdIndexRouteImport } from './routes/projects.$projectId.index'
import { Route as ProjectsProjectIdTestsRouteImport } from './routes/projects.$projectId.tests'
import { Route as ProjectsProjectIdLabelsRouteImport } from './routes/projects.$projectId.labels'
import { Route as ProjectsProjectIdDiagramRouteImport } from './routes/projects.$projectId.diagram'
import { Route as ProjectsProjectIdCutListRouteImport } from './routes/projects.$projectId.cut-list'
import { Route as ProjectsProjectIdBomRouteImport } from './routes/projects.$projectId.bom'
import { Route as ProjectsProjectIdBoardRouteImport } from './routes/projects.$projectId.board'

const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSdkRoute = DocsSdkRouteImport.update({
  id: '/sdk',
  path: '/sdk',
  getParentRoute: () => DocsRoute,
} as any)
const DocsRulesRoute = DocsRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => DocsRoute,
} as any)
const DocsDslRoute = DocsDslRouteImport.update({
  id: '/dsl',
  path: '/dsl',
  getParentRoute: () => DocsRoute,
} as any)
const DocsCliRoute = DocsCliRouteImport.update({
  id: '/cli',
  path: '/cli',
  getParentRoute: () => DocsRoute,
} as any)
const DocsArtifactsRoute = DocsArtifactsRouteImport.update({
  id: '/artifacts',
  path: '/artifacts',
  getParentRoute: () => DocsRoute,
} as any)
const DocsAiRoute = DocsAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => DocsRoute,
} as any)
const ProjectsProjectIdIndexRoute = ProjectsProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdTestsRoute = ProjectsProjectIdTestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdLabelsRoute = ProjectsProjectIdLabelsRouteImport.update({
  id: '/labels',
  path: '/labels',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdDiagramRoute =
  ProjectsProjectIdDiagramRouteImport.update({
    id: '/diagram',
    path: '/diagram',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdCutListRoute =
  ProjectsProjectIdCutListRouteImport.update({
    id: '/cut-list',
    path: '/cut-list',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdBomRoute = ProjectsProjectIdBomRouteImport.update({
  id: '/bom',
  path: '/bom',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdBoardRoute = ProjectsProjectIdBoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/docs/ai': typeof DocsAiRoute
  '/docs/artifacts': typeof DocsArtifactsRoute
  '/docs/cli': typeof DocsCliRoute
  '/docs/dsl': typeof DocsDslRoute
  '/docs/rules': typeof DocsRulesRoute
  '/docs/sdk': typeof DocsSdkRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/docs/': typeof DocsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$projectId/board': typeof ProjectsProjectIdBoardRoute
  '/projects/$projectId/bom': typeof ProjectsProjectIdBomRoute
  '/projects/$projectId/cut-list': typeof ProjectsProjectIdCutListRoute
  '/projects/$projectId/diagram': typeof ProjectsProjectIdDiagramRoute
  '/projects/$projectId/labels': typeof ProjectsProjectIdLabelsRoute
  '/projects/$projectId/tests': typeof ProjectsProjectIdTestsRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs/ai': typeof DocsAiRoute
  '/docs/artifacts': typeof DocsArtifactsRoute
  '/docs/cli': typeof DocsCliRoute
  '/docs/dsl': typeof DocsDslRoute
  '/docs/rules': typeof DocsRulesRoute
  '/docs/sdk': typeof DocsSdkRoute
  '/docs': typeof DocsIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/projects/$projectId/board': typeof ProjectsProjectIdBoardRoute
  '/projects/$projectId/bom': typeof ProjectsProjectIdBomRoute
  '/projects/$projectId/cut-list': typeof ProjectsProjectIdCutListRoute
  '/projects/$projectId/diagram': typeof ProjectsProjectIdDiagramRoute
  '/projects/$projectId/labels': typeof ProjectsProjectIdLabelsRoute
  '/projects/$projectId/tests': typeof ProjectsProjectIdTestsRoute
  '/projects/$projectId': typeof ProjectsProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/docs/ai': typeof DocsAiRoute
  '/docs/artifacts': typeof DocsArtifactsRoute
  '/docs/cli': typeof DocsCliRoute
  '/docs/dsl': typeof DocsDslRoute
  '/docs/rules': typeof DocsRulesRoute
  '/docs/sdk': typeof DocsSdkRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/docs/': typeof DocsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$projectId/board': typeof ProjectsProjectIdBoardRoute
  '/projects/$projectId/bom': typeof ProjectsProjectIdBomRoute
  '/projects/$projectId/cut-list': typeof ProjectsProjectIdCutListRoute
  '/projects/$projectId/diagram': typeof ProjectsProjectIdDiagramRoute
  '/projects/$projectId/labels': typeof ProjectsProjectIdLabelsRoute
  '/projects/$projectId/tests': typeof ProjectsProjectIdTestsRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/docs/ai'
    | '/docs/artifacts'
    | '/docs/cli'
    | '/docs/dsl'
    | '/docs/rules'
    | '/docs/sdk'
    | '/projects/$projectId'
    | '/docs/'
    | '/projects/'
    | '/projects/$projectId/board'
    | '/projects/$projectId/bom'
    | '/projects/$projectId/cut-list'
    | '/projects/$projectId/diagram'
    | '/projects/$projectId/labels'
    | '/projects/$projectId/tests'
    | '/projects/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs/ai'
    | '/docs/artifacts'
    | '/docs/cli'
    | '/docs/dsl'
    | '/docs/rules'
    | '/docs/sdk'
    | '/docs'
    | '/projects'
    | '/projects/$projectId/board'
    | '/projects/$projectId/bom'
    | '/projects/$projectId/cut-list'
    | '/projects/$projectId/diagram'
    | '/projects/$projectId/labels'
    | '/projects/$projectId/tests'
    | '/projects/$projectId'
  id:
    | '__root__'
    | '/'
    | '/docs'
    | '/docs/ai'
    | '/docs/artifacts'
    | '/docs/cli'
    | '/docs/dsl'
    | '/docs/rules'
    | '/docs/sdk'
    | '/projects/$projectId'
    | '/docs/'
    | '/projects/'
    | '/projects/$projectId/board'
    | '/projects/$projectId/bom'
    | '/projects/$projectId/cut-list'
    | '/projects/$projectId/diagram'
    | '/projects/$projectId/labels'
    | '/projects/$projectId/tests'
    | '/projects/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRoute: typeof DocsRouteWithChildren
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRouteWithChildren
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/sdk': {
      id: '/docs/sdk'
      path: '/sdk'
      fullPath: '/docs/sdk'
      preLoaderRoute: typeof DocsSdkRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/rules': {
      id: '/docs/rules'
      path: '/rules'
      fullPath: '/docs/rules'
      preLoaderRoute: typeof DocsRulesRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/dsl': {
      id: '/docs/dsl'
      path: '/dsl'
      fullPath: '/docs/dsl'
      preLoaderRoute: typeof DocsDslRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/cli': {
      id: '/docs/cli'
      path: '/cli'
      fullPath: '/docs/cli'
      preLoaderRoute: typeof DocsCliRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/artifacts': {
      id: '/docs/artifacts'
      path: '/artifacts'
      fullPath: '/docs/artifacts'
      preLoaderRoute: typeof DocsArtifactsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/ai': {
      id: '/docs/ai'
      path: '/ai'
      fullPath: '/docs/ai'
      preLoaderRoute: typeof DocsAiRouteImport
      parentRoute: typeof DocsRoute
    }
    '/projects/$projectId/': {
      id: '/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof ProjectsProjectIdIndexRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/tests': {
      id: '/projects/$projectId/tests'
      path: '/tests'
      fullPath: '/projects/$projectId/tests'
      preLoaderRoute: typeof ProjectsProjectIdTestsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/labels': {
      id: '/projects/$projectId/labels'
      path: '/labels'
      fullPath: '/projects/$projectId/labels'
      preLoaderRoute: typeof ProjectsProjectIdLabelsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/diagram': {
      id: '/projects/$projectId/diagram'
      path: '/diagram'
      fullPath: '/projects/$projectId/diagram'
      preLoaderRoute: typeof ProjectsProjectIdDiagramRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/cut-list': {
      id: '/projects/$projectId/cut-list'
      path: '/cut-list'
      fullPath: '/projects/$projectId/cut-list'
      preLoaderRoute: typeof ProjectsProjectIdCutListRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/bom': {
      id: '/projects/$projectId/bom'
      path: '/bom'
      fullPath: '/projects/$projectId/bom'
      preLoaderRoute: typeof ProjectsProjectIdBomRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/board': {
      id: '/projects/$projectId/board'
      path: '/board'
      fullPath: '/projects/$projectId/board'
      preLoaderRoute: typeof ProjectsProjectIdBoardRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
  }
}

interface DocsRouteChildren {
  DocsAiRoute: typeof DocsAiRoute
  DocsArtifactsRoute: typeof DocsArtifactsRoute
  DocsCliRoute: typeof DocsCliRoute
  DocsDslRoute: typeof DocsDslRoute
  DocsRulesRoute: typeof DocsRulesRoute
  DocsSdkRoute: typeof DocsSdkRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsAiRoute: DocsAiRoute,
  DocsArtifactsRoute: DocsArtifactsRoute,
  DocsCliRoute: DocsCliRoute,
  DocsDslRoute: DocsDslRoute,
  DocsRulesRoute: DocsRulesRoute,
  DocsSdkRoute: DocsSdkRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

interface ProjectsProjectIdRouteChildren {
  ProjectsProjectIdBoardRoute: typeof ProjectsProjectIdBoardRoute
  ProjectsProjectIdBomRoute: typeof ProjectsProjectIdBomRoute
  ProjectsProjectIdCutListRoute: typeof ProjectsProjectIdCutListRoute
  ProjectsProjectIdDiagramRoute: typeof ProjectsProjectIdDiagramRoute
  ProjectsProjectIdLabelsRoute: typeof ProjectsProjectIdLabelsRoute
  ProjectsProjectIdTestsRoute: typeof ProjectsProjectIdTestsRoute
  ProjectsProjectIdIndexRoute: typeof ProjectsProjectIdIndexRoute
}

const ProjectsProjectIdRouteChildren: ProjectsProjectIdRouteChildren = {
  ProjectsProjectIdBoardRoute: ProjectsProjectIdBoardRoute,
  ProjectsProjectIdBomRoute: ProjectsProjectIdBomRoute,
  ProjectsProjectIdCutListRoute: ProjectsProjectIdCutListRoute,
  ProjectsProjectIdDiagramRoute: ProjectsProjectIdDiagramRoute,
  ProjectsProjectIdLabelsRoute: ProjectsProjectIdLabelsRoute,
  ProjectsProjectIdTestsRoute: ProjectsProjectIdTestsRoute,
  ProjectsProjectIdIndexRoute: ProjectsProjectIdIndexRoute,
}

const ProjectsProjectIdRouteWithChildren =
  ProjectsProjectIdRoute._addFileChildren(ProjectsProjectIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRoute: DocsRouteWithChildren,
  ProjectsProjectIdRoute: ProjectsProjectIdRouteWithChildren,
  ProjectsIndexRoute: ProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
