/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as ProjectsProjectIdIndexRouteImport } from './routes/projects.$projectId.index'
import { Route as ProjectsProjectIdTestsRouteImport } from './routes/projects.$projectId.tests'
import { Route as ProjectsProjectIdSourceRouteImport } from './routes/projects.$projectId.source'
import { Route as ProjectsProjectIdLabelsRouteImport } from './routes/projects.$projectId.labels'
import { Route as ProjectsProjectIdDiagramRouteImport } from './routes/projects.$projectId.diagram'
import { Route as ProjectsProjectIdCutListRouteImport } from './routes/projects.$projectId.cut-list'
import { Route as ProjectsProjectIdBomRouteImport } from './routes/projects.$projectId.bom'
import { Route as ProjectsProjectIdBoardRouteImport } from './routes/projects.$projectId.board'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdIndexRoute = ProjectsProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdTestsRoute = ProjectsProjectIdTestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdSourceRoute = ProjectsProjectIdSourceRouteImport.update({
  id: '/source',
  path: '/source',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdLabelsRoute = ProjectsProjectIdLabelsRouteImport.update({
  id: '/labels',
  path: '/labels',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdDiagramRoute =
  ProjectsProjectIdDiagramRouteImport.update({
    id: '/diagram',
    path: '/diagram',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdCutListRoute =
  ProjectsProjectIdCutListRouteImport.update({
    id: '/cut-list',
    path: '/cut-list',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdBomRoute = ProjectsProjectIdBomRouteImport.update({
  id: '/bom',
  path: '/bom',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdBoardRoute = ProjectsProjectIdBoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$projectId/board': typeof ProjectsProjectIdBoardRoute
  '/projects/$projectId/bom': typeof ProjectsProjectIdBomRoute
  '/projects/$projectId/cut-list': typeof ProjectsProjectIdCutListRoute
  '/projects/$projectId/diagram': typeof ProjectsProjectIdDiagramRoute
  '/projects/$projectId/labels': typeof ProjectsProjectIdLabelsRoute
  '/projects/$projectId/source': typeof ProjectsProjectIdSourceRoute
  '/projects/$projectId/tests': typeof ProjectsProjectIdTestsRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/projects/$projectId/board': typeof ProjectsProjectIdBoardRoute
  '/projects/$projectId/bom': typeof ProjectsProjectIdBomRoute
  '/projects/$projectId/cut-list': typeof ProjectsProjectIdCutListRoute
  '/projects/$projectId/diagram': typeof ProjectsProjectIdDiagramRoute
  '/projects/$projectId/labels': typeof ProjectsProjectIdLabelsRoute
  '/projects/$projectId/source': typeof ProjectsProjectIdSourceRoute
  '/projects/$projectId/tests': typeof ProjectsProjectIdTestsRoute
  '/projects/$projectId': typeof ProjectsProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$projectId/board': typeof ProjectsProjectIdBoardRoute
  '/projects/$projectId/bom': typeof ProjectsProjectIdBomRoute
  '/projects/$projectId/cut-list': typeof ProjectsProjectIdCutListRoute
  '/projects/$projectId/diagram': typeof ProjectsProjectIdDiagramRoute
  '/projects/$projectId/labels': typeof ProjectsProjectIdLabelsRoute
  '/projects/$projectId/source': typeof ProjectsProjectIdSourceRoute
  '/projects/$projectId/tests': typeof ProjectsProjectIdTestsRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/projects/$projectId'
    | '/projects/'
    | '/projects/$projectId/board'
    | '/projects/$projectId/bom'
    | '/projects/$projectId/cut-list'
    | '/projects/$projectId/diagram'
    | '/projects/$projectId/labels'
    | '/projects/$projectId/source'
    | '/projects/$projectId/tests'
    | '/projects/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/projects'
    | '/projects/$projectId/board'
    | '/projects/$projectId/bom'
    | '/projects/$projectId/cut-list'
    | '/projects/$projectId/diagram'
    | '/projects/$projectId/labels'
    | '/projects/$projectId/source'
    | '/projects/$projectId/tests'
    | '/projects/$projectId'
  id:
    | '__root__'
    | '/'
    | '/projects/$projectId'
    | '/projects/'
    | '/projects/$projectId/board'
    | '/projects/$projectId/bom'
    | '/projects/$projectId/cut-list'
    | '/projects/$projectId/diagram'
    | '/projects/$projectId/labels'
    | '/projects/$projectId/source'
    | '/projects/$projectId/tests'
    | '/projects/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRouteWithChildren
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/': {
      id: '/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof ProjectsProjectIdIndexRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/tests': {
      id: '/projects/$projectId/tests'
      path: '/tests'
      fullPath: '/projects/$projectId/tests'
      preLoaderRoute: typeof ProjectsProjectIdTestsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/source': {
      id: '/projects/$projectId/source'
      path: '/source'
      fullPath: '/projects/$projectId/source'
      preLoaderRoute: typeof ProjectsProjectIdSourceRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/labels': {
      id: '/projects/$projectId/labels'
      path: '/labels'
      fullPath: '/projects/$projectId/labels'
      preLoaderRoute: typeof ProjectsProjectIdLabelsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/diagram': {
      id: '/projects/$projectId/diagram'
      path: '/diagram'
      fullPath: '/projects/$projectId/diagram'
      preLoaderRoute: typeof ProjectsProjectIdDiagramRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/cut-list': {
      id: '/projects/$projectId/cut-list'
      path: '/cut-list'
      fullPath: '/projects/$projectId/cut-list'
      preLoaderRoute: typeof ProjectsProjectIdCutListRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/bom': {
      id: '/projects/$projectId/bom'
      path: '/bom'
      fullPath: '/projects/$projectId/bom'
      preLoaderRoute: typeof ProjectsProjectIdBomRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/board': {
      id: '/projects/$projectId/board'
      path: '/board'
      fullPath: '/projects/$projectId/board'
      preLoaderRoute: typeof ProjectsProjectIdBoardRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
  }
}

interface ProjectsProjectIdRouteChildren {
  ProjectsProjectIdBoardRoute: typeof ProjectsProjectIdBoardRoute
  ProjectsProjectIdBomRoute: typeof ProjectsProjectIdBomRoute
  ProjectsProjectIdCutListRoute: typeof ProjectsProjectIdCutListRoute
  ProjectsProjectIdDiagramRoute: typeof ProjectsProjectIdDiagramRoute
  ProjectsProjectIdLabelsRoute: typeof ProjectsProjectIdLabelsRoute
  ProjectsProjectIdSourceRoute: typeof ProjectsProjectIdSourceRoute
  ProjectsProjectIdTestsRoute: typeof ProjectsProjectIdTestsRoute
  ProjectsProjectIdIndexRoute: typeof ProjectsProjectIdIndexRoute
}

const ProjectsProjectIdRouteChildren: ProjectsProjectIdRouteChildren = {
  ProjectsProjectIdBoardRoute: ProjectsProjectIdBoardRoute,
  ProjectsProjectIdBomRoute: ProjectsProjectIdBomRoute,
  ProjectsProjectIdCutListRoute: ProjectsProjectIdCutListRoute,
  ProjectsProjectIdDiagramRoute: ProjectsProjectIdDiagramRoute,
  ProjectsProjectIdLabelsRoute: ProjectsProjectIdLabelsRoute,
  ProjectsProjectIdSourceRoute: ProjectsProjectIdSourceRoute,
  ProjectsProjectIdTestsRoute: ProjectsProjectIdTestsRoute,
  ProjectsProjectIdIndexRoute: ProjectsProjectIdIndexRoute,
}

const ProjectsProjectIdRouteWithChildren =
  ProjectsProjectIdRoute._addFileChildren(ProjectsProjectIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRouteWithChildren,
  ProjectsIndexRoute: ProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
