import { useCallback, useRef, useState } from "react"
import type { Hir } from "@grayhaven/nerve"
import { Button } from "../ui/button.js"

/**
 * Interactive sheet wrapper for exporter-generated SVG (diagram + board).
 * All interactivity is view-layer only — the SVG string stays the
 * byte-deterministic artifact.
 *
 * - Hover net-highlighting: delegated pointer events (one listener pair
 *   survives every dangerouslySetInnerHTML swap) toggle .hl on elements
 *   sharing the hovered data-wire and .dimmed on the sheet.
 * - Zoom: ctrl/cmd+wheel scales the SVG via CSS width (zoom-to-cursor by
 *   adjusting the scroll container); native scrollbars keep panning calm.
 * - Copy SVG: the deterministic markup pastes into Figma/Inkscape as vectors.
 */
export function SchematicSheet({
  svg,
  filename,
  hir,
  kind
}: {
  svg: string
  filename: string
  hir: Hir
  kind: "schematic" | "board"
}) {
  const paneRef = useRef<HTMLDivElement | null>(null)
  const zoomRef = useRef(1)
  const [copied, setCopied] = useState(false)

  const attach = useCallback((pane: HTMLDivElement | null) => {
    paneRef.current = pane
    if (pane === null) return

    const clear = () => {
      pane.classList.remove("net-hover")
      for (const el of pane.querySelectorAll(".hl")) el.classList.remove("hl")
    }
    const over = (e: PointerEvent) => {
      const ref = (e.target as Element).closest?.("[data-wire]")?.getAttribute("data-wire")
      clear()
      if (ref === null || ref === undefined) return
      pane.classList.add("net-hover")
      for (const el of pane.querySelectorAll(`[data-wire="${CSS.escape(ref)}"]`)) {
        el.classList.add("hl")
      }
    }
    const applyZoom = (z: number) => {
      const svgEl = pane.querySelector("svg")
      if (svgEl === null) return
      const natural = Number(svgEl.getAttribute("width"))
      if (Number.isNaN(natural)) return
      svgEl.style.width = `${natural * z}px`
      svgEl.style.height = "auto"
    }
    const wheel = (e: WheelEvent) => {
      if (!e.ctrlKey && !e.metaKey) return
      e.preventDefault()
      const scroller = pane.closest(".render-pane") ?? pane
      const rect = pane.getBoundingClientRect()
      const prev = zoomRef.current
      const next = Math.min(4, Math.max(0.4, prev * (e.deltaY < 0 ? 1.15 : 1 / 1.15)))
      if (next === prev) return
      // Zoom-to-cursor: keep the point under the pointer stationary.
      const px = e.clientX - rect.left
      const py = e.clientY - rect.top
      zoomRef.current = next
      applyZoom(next)
      scroller.scrollLeft += px * (next / prev - 1)
      scroller.scrollTop += py * (next / prev - 1)
    }
    pane.addEventListener("pointerover", over)
    pane.addEventListener("pointerleave", clear)
    pane.addEventListener("wheel", wheel, { passive: false })
    applyZoom(zoomRef.current)
    // React 19 ref cleanup: colocated teardown.
    return () => {
      pane.removeEventListener("pointerover", over)
      pane.removeEventListener("pointerleave", clear)
      pane.removeEventListener("wheel", wheel)
    }
  }, [])

  const copy = () => {
    void navigator.clipboard.writeText(svg).then(() => {
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    })
  }
  const downloadBlob = (contents: string, name: string, type: string) => {
    const url = URL.createObjectURL(new Blob([contents], { type }))
    const a = document.createElement("a")
    a.href = url
    a.download = name
    a.click()
    URL.revokeObjectURL(url)
  }
  const download = () => downloadBlob(svg, filename, "image/svg+xml")
  // Self-contained interactive viewer (hover nets, zoom, pan) — opens
  // anywhere, no app needed. Lazy: shares the exporters chunk with the
  // packet export.
  const downloadHtml = async () => {
    const { schematicHtml, boardHtml } = await import("@grayhaven/nerve-exporters")
    const html = kind === "schematic" ? schematicHtml(hir) : boardHtml(hir)
    downloadBlob(html, filename.replace(/\.svg$/, ".html"), "text/html")
  }

  return (
    <div className="sheet-wrap">
      <div className="sheet-actions">
        <Button variant="ghost" size="xs" onClick={copy}>
          {copied ? "Copied ✓" : "Copy SVG"}
        </Button>
        <Button variant="ghost" size="xs" onClick={download}>
          Download SVG
        </Button>
        <Button variant="ghost" size="xs" onClick={() => void downloadHtml()}>
          Download HTML
        </Button>
        <span className="sheet-hint">⌘+scroll to zoom · hover a wire</span>
      </div>
      <div
        className="diagram-pane"
        ref={attach}
        // axe scrollable-region-focusable: keyboard users must be able to
        // scroll the sheet.
        tabIndex={0}
        role="region"
        aria-label={`${kind} drawing`}
        // The SVG is generated by our own deterministic renderer from HIR.
        dangerouslySetInnerHTML={{ __html: svg }}
      />
    </div>
  )
}
