/**
 * Self-contained interactive HTML viewer for a schematic (PRD §27 family).
 * Deterministic: a fixed template wrapping the byte-deterministic SVG plus
 * ~50 lines of inline vanilla JS for net hover-highlighting, ctrl/cmd-wheel
 * zoom, and drag-to-pan. Opens anywhere a browser exists — no app, no
 * network. The SVG inside remains the canonical artifact; the HTML is a
 * portable viewing surface over it (it never re-lays-out the drawing).
 */
import type { Hir } from "@grayhaven/nerve"
import { schematicSvg } from "./svg.js"
import { boardSvg } from "./board.js"
import { connectorFacesSvg } from "./faces.js"

const viewer = (title: string, svg: string): string => `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${title}</title>
<style>
  body { margin: 0; background: #e8e6e1; font-family: ui-monospace, SFMono-Regular, Menlo, monospace; }
  header { padding: 8px 14px; font-size: 11px; letter-spacing: 0.04em; text-transform: uppercase; color: #555; border-bottom: 1px solid #d4d1ca; background: #f1efe9; }
  #pane { overflow: auto; height: calc(100vh - 33px); cursor: grab; }
  #pane.panning { cursor: grabbing; }
  svg { display: block; margin: 16px auto; box-shadow: 0 1px 4px rgb(0 0 0 / 0.12); }
  svg text { paint-order: stroke; stroke: #fafafa; stroke-width: 3px; stroke-linejoin: round; }
  svg [data-wire] { transition: opacity 150ms ease-out; }
  #pane.hover svg [data-wire]:not(.hl) { opacity: 0.18; }
  #pane.hover svg path[data-wire].hl { stroke-width: 3; }
</style>
</head>
<body>
<header>${title} — generated by Grayhaven Nerve · hover a wire · ctrl/cmd+scroll zooms · drag pans</header>
<div id="pane">${svg}</div>
<script>
(() => {
  const pane = document.getElementById("pane");
  const svg = pane.querySelector("svg");
  const natural = Number(svg.getAttribute("width"));
  let zoom = 1;
  const clear = () => { pane.classList.remove("hover"); for (const el of pane.querySelectorAll(".hl")) el.classList.remove("hl"); };
  pane.addEventListener("pointerover", (e) => {
    const ref = e.target.closest?.("[data-wire]")?.getAttribute("data-wire");
    clear();
    if (!ref) return;
    pane.classList.add("hover");
    for (const el of pane.querySelectorAll('[data-wire="' + CSS.escape(ref) + '"]')) el.classList.add("hl");
  });
  pane.addEventListener("pointerleave", clear);
  pane.addEventListener("wheel", (e) => {
    if (!e.ctrlKey && !e.metaKey) return;
    e.preventDefault();
    const prev = zoom;
    zoom = Math.min(4, Math.max(0.4, zoom * (e.deltaY < 0 ? 1.15 : 1 / 1.15)));
    if (zoom === prev) return;
    svg.style.width = natural * zoom + "px";
    svg.style.height = "auto";
    pane.scrollLeft += e.offsetX * (zoom / prev - 1);
    pane.scrollTop += e.offsetY * (zoom / prev - 1);
  }, { passive: false });
  let drag = null;
  pane.addEventListener("pointerdown", (e) => { drag = { x: e.clientX, y: e.clientY, sl: pane.scrollLeft, st: pane.scrollTop }; pane.classList.add("panning"); });
  window.addEventListener("pointermove", (e) => { if (!drag) return; pane.scrollLeft = drag.sl - (e.clientX - drag.x); pane.scrollTop = drag.st - (e.clientY - drag.y); });
  window.addEventListener("pointerup", () => { drag = null; pane.classList.remove("panning"); });
})();
</script>
</body>
</html>
`

/** Interactive schematic viewer. Deterministic for identical HIR. */
export const schematicHtml = (hir: Hir): string =>
  viewer(`${hir.harness.id} — schematic · rev ${hir.harness.revision}`, schematicSvg(hir))

/** Interactive board viewer. Deterministic for identical HIR. */
export const boardHtml = (hir: Hir): string =>
  viewer(`${hir.harness.id} — board · rev ${hir.harness.revision}`, boardSvg(hir))

/** Interactive connector-faces viewer. Deterministic for identical HIR. */
export const facesHtml = (hir: Hir): string =>
  viewer(`${hir.harness.id} — connector faces · rev ${hir.harness.revision}`, connectorFacesSvg(hir))
