export {
  branchMissingLabel,
  branchParentInvalid,
  breakoutTighterThanBendRadius,
  breakoutTighterThanBendRadiusWith,
  builtinRules,
  builtinRulesWith,
  bundleOverSleeveCapacity,
  bundleOverSleeveCapacityWith,
  cableConductorOverflow,
  cavityLayoutMismatch,
  connectorCurrentExceeded,
  connectorVoltageExceeded,
  contactCountExceedsPinCount,
  differentialPairNotTwisted,
  emcAggressorVictimShareBranch,
  gaugeCurrentMismatchWith,
  gaugeCurrentMismatch,
  gaugeOutsideConnectorRange,
  missingGroundReturn,
  missingRevision,
  missingTerminal,
  missingWireColor,
  missingWireGauge,
  missingSeal,
  missingWireLength,
  missingCableConductor,
  multipleWiresIntoPin,
  nonPositiveWireLength,
  orphanedDifferentialHalf,
  overcurrentExceedsConductor,
  overcurrentExceedsConductorWith,
  requireApprovedParts,
  reservedPinAssigned,
  sealIncompatible,
  shieldDrainUnconnected,
  spliceMissingNotes,
  terminalIncompatible,
  twistGroupGaugeMismatch,
  twistGroupTooSmall,
  uncoveredNet,
  wireTempBelowAmbient,
  unconnectedAssignedPin,
  unparseableGauge,
  voltageRatingBelowSignal,
  wireSignalMismatch
} from "./rules.js"

export {
  AMPACITY_BY_AWG,
  differentialPartner,
  isGroundSignal,
  isPowerSignal,
  isShieldSignal,
  parseAwg,
  requiredAwgForCurrent
} from "./wire-data.js"

export {
  codesToNumbers,
  RULE_CATEGORY_BANDS,
  ruleCategory,
  ruleCodeFromNumber,
  ruleCodeNumber,
  type RuleCategory
} from "./code-numbers.js"
