/**
 * Project scaffolding: `nerve init` (a project that can actually resolve
 * its own imports — package.json/tsconfig/.gitignore, not just two files)
 * and `nerve setup` (CI workflows: validate, snapshot, and the
 * byte-reproducibility check nobody else can offer).
 *
 * Every file is per-file refuse-to-overwrite: existing files are skipped
 * with a notice, never clobbered.
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"
import type { Io } from "./index.js"

/** This CLI's own version — scaffolded projects pin the same line. */
export const cliVersion = (): string => {
  try {
    // package.json sits one level above both src/ (dev) and dist/ (published).
    const pkgPath = join(dirname(fileURLToPath(import.meta.url)), "..", "package.json")
    const pkg = JSON.parse(readFileSync(pkgPath, "utf8")) as { version?: string }
    return pkg.version ?? "latest"
  } catch {
    return "latest"
  }
}

const INIT_CONFIG = `import { defineConfig } from "@grayhaven/nerve"

export default defineConfig({
  units: "mm",
  entry: "./src/main.harness.ts",
  defaultWireTolerance: 10,
  outputDir: "dist",
  rules: {
    missingWireColor: "error",
    missingWireLength: "warning"
  },
  exports: { csv: true, svg: true }
})
`

const INIT_HARNESS = `import { harness, connector, wire } from "@grayhaven/nerve"
import { part } from "@grayhaven/nerve-connectors"

const j1 = connector("J1", part("ph-2"), {
  pins: { 1: "PWR_12V", 2: "GND" },
})

const j2 = connector("J2", part("ph-2"), {
  pins: { 1: "PWR_12V", 2: "GND" },
})

export default harness("my-first-harness", {
  revision: "A",
  units: "mm",
  connectors: [j1, j2],
  wires: [
    wire("W1", j1.pin(1), j2.pin(1), { signal: "PWR_12V", color: "red", gauge: "26AWG", length: 150 }),
    wire("W2", j1.pin(2), j2.pin(2), { signal: "GND", color: "black", gauge: "26AWG", length: 150 }),
  ],
})
`

const initPackageJson = (version: string): string =>
  JSON.stringify(
    {
      name: "my-harness",
      private: true,
      version: "0.1.0",
      type: "module",
      scripts: {
        compile: "nerve compile",
        validate: "nerve validate",
        dev: "nerve dev",
        export: "nerve export",
        snapshot: "nerve snapshot"
      },
      dependencies: {
        "@grayhaven/nerve": `^${version}`,
        "@grayhaven/nerve-connectors": `^${version}`
      },
      devDependencies: {
        "@grayhaven/nerve-cli": `^${version}`,
        typescript: "^5.8.0"
      }
    },
    null,
    2
  ) + "\n"

const INIT_TSCONFIG = `{
  "compilerOptions": {
    "target": "ES2022",
    "module": "NodeNext",
    "moduleResolution": "NodeNext",
    "strict": true,
    "noEmit": true,
    "skipLibCheck": true
  },
  "include": ["src", "nerve.config.ts"]
}
`

const INIT_GITIGNORE = `node_modules/
dist/
`

/** init: a complete runnable project. */
export const initFiles = (version: string): ReadonlyMap<string, string> =>
  new Map([
    ["nerve.config.ts", INIT_CONFIG],
    ["src/main.harness.ts", INIT_HARNESS],
    ["package.json", initPackageJson(version)],
    ["tsconfig.json", INIT_TSCONFIG],
    [".gitignore", INIT_GITIGNORE]
  ])

const VALIDATE_YML = `# Generated by \`nerve setup\` — edit freely, setup never overwrites.
name: Nerve validate
on:
  push:
  pull_request:
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm ci || npm install
      # Exit 1 on any HK-* error; the release gate fails closed.
      - run: npx nerve validate
`

const SNAPSHOT_YML = `# Generated by \`nerve setup\` — edit freely, setup never overwrites.
name: Nerve snapshot
on:
  push:
  pull_request:
jobs:
  snapshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm ci || npm install
      # Byte-exact: any drawing change fails until snapshots are
      # deliberately refreshed with \`nerve snapshot --update\`.
      - run: npx nerve snapshot --ci
      - if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: snapshot-diffs
          path: "**/__snapshots__/*.diff.png"
`

const REPRODUCE_YML = `# Generated by \`nerve setup\` — edit freely, setup never overwrites.
# Byte-reproducibility: the committed dist/harness.json must rebuild
# identically from source. Deterministic compilation makes this checkable;
# \`nerve diff\` exits 1 on any semantic difference.
name: Nerve reproduce
on:
  push:
  pull_request:
jobs:
  reproduce:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm ci || npm install
      - run: |
          if [ -f dist/harness.json ]; then
            npx nerve compile --out /tmp/fresh
            npx nerve diff dist/harness.json /tmp/fresh/harness.json
          else
            echo "No committed dist/harness.json — nothing to reproduce."
          fi
`

/** setup: CI workflows under .github/workflows/. */
export const setupFiles = (): ReadonlyMap<string, string> =>
  new Map([
    [".github/workflows/nerve-validate.yml", VALIDATE_YML],
    [".github/workflows/nerve-snapshot.yml", SNAPSHOT_YML],
    [".github/workflows/nerve-reproduce.yml", REPRODUCE_YML]
  ])

/** Write files per-file refuse-to-overwrite; report what happened. */
export const writeScaffold = (
  dir: string,
  files: ReadonlyMap<string, string>,
  io: Io
): { wrote: number; skipped: number } => {
  let wrote = 0
  let skipped = 0
  for (const [rel, content] of files) {
    const path = join(dir, rel)
    if (existsSync(path)) {
      skipped += 1
      io.out(`  ${rel} (exists, skipped)`)
      continue
    }
    mkdirSync(dirname(path), { recursive: true })
    writeFileSync(path, content)
    wrote += 1
    io.out(`  ${rel}`)
  }
  return { wrote, skipped }
}
